EmployessMVCAPI/Models/DataTransferObjects/EmployeDto.cs
namespace EmployessMVCAPI.Models.DataTransferObjects
{
    public class EmployessDto: Data
    {
        public string status { get; set; }
        public List<Data> data { get; set; }
        public string message { get; set; }
        
    }

	public class EmployeDto: Data
	{
		public string status { get; set; }
		public Data data { get; set; }
		public string message { get; set; }

	}

	public class Data
    {
        public int id { get; set; }
        public string employee_name { get; set; }
        public int employee_salary { get; set; }
        public int employee_age { get; set; }
        public string profile_image { get; set; }
    }

}

EmployessMVCAPI/Models/ErrorViewModel.cs
namespace EmployessMVCAPI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmployessMVCAPI/Models/Validation.cs
namespace EmployessMVCAPI.Models
{
	public class Validation
	{
		public bool showMessage { get; set; }

	}
}

EmployessMVCAPI/Controllers/EmployeController.cs
using EmployessMVCAPI.Models;
using EmployessMVCAPI.Models.DataTransferObjects;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace EmployessMVCAPI.Controllers
{
	public class EmployeController : Controller
	{

		private readonly BaseRepository _baseRepository;
		public EmployeController()
		{
			_baseRepository = new BaseRepository();

		}
		public IActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public async Task<ActionResult> GetEmployessAsync(string id)
		{
			Validation validate = new Validation()
			{
				showMessage = true,
			};

			try
			{
				int valueId = (int)((id == null) ? 0 : Int64.Parse(id));
				string response = valueId > 0
				? await _baseRepository.GetEmployeeByIdAsync(Int32.Parse(id))
				: await _baseRepository.GetEmployeesAsync();

				if (response != null)
				{
					if (valueId > 0)
					{
						var employessResponse = JsonConvert.DeserializeObject<EmployeDto>(response);
						if (employessResponse.data != null)
						{
							return View("~/Views/Employe/IndexSingle.cshtml", employessResponse.data);
						}
						else
						{
							return View("~/Views/Home/Index.cshtml", validate);
						}
					}
					else
					{
						var employeeResponse = JsonConvert.DeserializeObject<EmployessDto>(response);
						return View("~/Views/Employe/Index.cshtml", employeeResponse.data);
					}
				}
				else
				{
					return View("~/Views/Home/Index.cshtml", validate);
				}
			}
			catch (Exception ex)
			{
				validate.showMessage = true;
				return View("~/Views/Home/Index.cshtml", validate);
			}


		}

	}

}

EmployessMVCAPI/Controllers/HomeController.cs
using EmployessMVCAPI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmployessMVCAPI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
			Validation validate= new Validation()
            {
                showMessage = false,  
            };

			return View(validate);
        }
        //probando
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmployessMVCAPI/Views/Employe/Index.cshtml
@using EmployessMVCAPI.Models.DataTransferObjects

@model List<Data>

<h2>List of Employess</h2>

<table class="table table-bordered table-striped">
	<thead class="thead-dark">
		<tr>
			<th class="text-center">Id</th>
			<th class="text-center">Employee Name</th>
			<th class="text-center">Employee Salary</th>
			<th class="text-center">Employee Annual Salary</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var employee in Model)
		{
			<tr>
				<td class="text-center">@employee.id</td>
				<td>@employee.employee_name</td>
				<td class="text-right">@string.Format("{0:N0}", employee.employee_salary)</td>
				<td class="text-right">@string.Format("{0:N0}", employee.employee_salary * 12)</td>
			</tr>
		}
	</tbody>
</table>


<a asp-area="" asp-controller="Home" asp-action="Index">Back to Home</a>

EmployessMVCAPI/Views/Employe/IndexSingle.cshtml
@using EmployessMVCAPI.Models.DataTransferObjects

@model Data

<h2>Result by Id</h2>
<p>Sended Id: @Model.id</p>

<table class="table table-bordered table-striped">
	<thead class="thead-dark">
		<tr>
			<th class="text-center">Id</th>
			<th class="text-center">Employee Name</th>
			<th class="text-center">Employee Salary</th>
			<th class="text-center">Employee Annual Salary</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td class="text-center">@Model.id</td>
			<td>@Model.employee_name</td>
			<td class="text-right">@string.Format("{0:N0}", Model.employee_salary)</td>
			<td class="text-right">@string.Format("{0:N0}", Model.employee_salary * 12)</td>
		</tr>
	</tbody>
</table>

<a asp-area="" asp-controller="Home" asp-action="Index">Back to Home</a>

EmployessMVCAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model Validation;

<h2>Find an Employe by Id</h2>
<p>If you do not know an Employee Id, press botton Send to check de List of Employess</p>


@if (@Model.showMessage)
{
    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label>Type a valid Employee Id</label>
        </div>
    </div>
}

@using (Html.BeginForm("GetEmployess", "Employe", FormMethod.Post, new { @class = "form" }))
{
    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label for="id">Id:</label>
                <input type="number" name="id" id="id" class="form-control form-control-sm" />
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Send</button>
}

EmployessMVCAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployessMVCAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmployessMVCAPI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Challenge</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>